akka {
    actor {
        provider = "cluster"
        serializers {
            java = "akka.serialization.JavaSerializer"
        }
        serialization-bindings {
            "atomatron.worker.agent.message.Message" = java
        }
        allow-java-serialization = on
        warn-about-java-serializer-usage = off
    }
    remote {
        artery {
            canonical.hostname = "127.0.0.1"
            canonical.port = 2551
        }
    }
    cluster {
        seed-nodes = ["akka://AmpSystem@127.0.0.1:2551"]
        downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"
    }
    extensions = ["akka.cluster.pubsub.DistributedPubSub"]
}
